// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class SkillsTable
{
    public int SkillId { get; set; }

    public string SkillName { get; set; }

    public virtual ICollection<StudTable> Students { get; set; } = new List<StudTable>();
}