// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class StudTable
{
    public int StudentId { get; set; }

    public string Name { get; set; }

    public int? Age { get; set; }

    public int Fees { get; set; }

    public string Gender { get; set; }

    public bool IsDeleted { get; set; }

    public string EmailId { get; set; }

    public string Skills { get; set; }
}